### ISSUE TITLE
ps3 controller joystick did not work

### ISSUE THREAD

**Issue by haniff8387** [Mango-kid/rbx1-software#1]
I am using your code for my robot arm project. I am using ps3 controller to control my robot. However, only the left gamepad that function, the joysticks and other buttons did not work. How should i fix this? Is it the code only work for Xbox controller or can it work on other normal controller? Thank you for your help.

**Comment by Mango-kid** [comment]
This is based on the Python Inputs library.  This library does not support that controller. A custom interface would have to be created using pygame to get the controller input.
